### ISSUE TITLE
Final Test - UG (save)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#254]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/85627654/230807440-e4850d3c-a629-49af-8b58-e4b8ebb7fef4.png">

wrong description of save - if data is corrupted, keying in 'save' results in a FRESH new state. Corrupted data is not reloaded. 

Note: Corrupted data will never be loaded, either users identify whats corrupting the data and amend or the data will be lost. 

So the description of this alert message as well as the corresponding portions in the UG have to be edited

**Comment by DeepanjaliDhawan** [comment]
I wrotee that the corrupted secrets will be overwritten by the new secrets....So that means in fresh new state and nowhere mention corrupted data will be reloaded... 

If any other suggestion.. please let me know now... Im not closing this issue yet.. 

Waiting for ur response.

**Comment by ollayf** [comment]
ok now i get both of your points. But i agree the phrasing is abit awkward. because of the repeated use of words like writing/ overwriting, etc. How about:

In the case of blahblah...
- Recommended: Users can use the save command OR continue using the app as per normal. All previous data will be erased when new data is loaded in.
- Try to recover the state of database.txt. You may have accidentally edited some characters in the database.txt file causing the corruption. In these cases, undoing these edits will cause the application to import the previous data on next load.
